version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: controleDeRoupasHospitalares
      MYSQL_ROOT_PASSWORD: infra@root-controlederoupa
    ports:
      - 3307:3306
    volumes:
      - ./data:/var/lib/mysql
